Update readme.md
cvyl/awesome-transgender pull request #3
Opened 2024-02-28 21:31 UTC by stark1tty

Added:
- Aesthetic line breaks.
- Navigation.
- Mastodon + Subsections.
- Misskey Section.
- UK Section.
- DIY and Skills Section.

Changed:
- Table of Contents.
- Minor aesthetic spacing fixes. 
- Reordered DIY & HRT into a DIY and Skills section.

Listen, I am straight and am not in this sphere, but I am happy to help. Feel free to fix my ignorance/wording. I will add some Lemmy servers once the other pull is merged.

2024-02-28 21:36 UTC, cvyl commented
Thank you very much for your contribution, unfortunately awesome's guidelines do not allow nestings in the table of contents. E.g.
- a
    - b
    - c
 - d
    - e
  
is allowed but 

- a
    - b
         - c
         - d
     - e
         - f
     - g

is not allowed

2024-02-28 21:37 UTC, cvyl requested changes
Depth of nesting. I recommend you check all requirements with "awesome-lint" https://www.npmjs.com/package/awesome-lint

2024-02-28 22:30 UTC, stark1tty commented
Oops, no worries. I have an idea on how to sort this. I will take a look in a bit but it may be a day or two.

2024-02-28 23:54 UTC, stark1tty reviewed
Removed List Levels and added more Reddit and Mastodon items.

2024-02-28 23:55 UTC, stark1tty commented
Should be alright now fingers crossed!

2024-02-29 09:26 UTC, cvyl commented
I am very sorry but there are still unresolved conflicts.

2024-03-02 23:22 UTC, BackHDLP commented
Is there a reason why you removed the lemmy links?

2024-03-03 18:13 UTC, cvyl commented
It seems blahaj.zone is broader than only lemmy, perhaps that's why. But I am not sure...

2024-04-02 22:35 UTC, googl267 commented
@BackHDLP lemmy.blahaj.zone is the correct link, blahaj.zone is their Sharkey instance

2026-02-04 21:12 UTC, closed without merging